---
# ------------------------------------------------------------------------------
# install php
# ------------------------------------------------------------------------------

- name: add php repositories
  apt_repository: repo="{{php_repository}}"
  when: php_repository is defined and php_repository != False

- name: open ssl and mcrypt
  apt: 
    state: present
    pkg: [
      'mcrypt',
      'openssl'
    ]

- name: install php
  apt: 
    pkg: "{{php_modules}}" 
    state: present
  notify: restart php

- name: ensure php starts at boot
  service: name='{{php_service_name}}' state=started enabled=yes


# ------------------------------------------------------------------------------
# install composer
# ------------------------------------------------------------------------------

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: self update composer
  shell: /usr/local/bin/composer self-update

# ------------------------------------------------------------------------------
# backup configs and configure php
# ------------------------------------------------------------------------------

# fpm
- name: get php-fpm ini backup stats
  stat: path='{{php_ini_dir}}/fpm/php.ini.original.bak' follow=False
  register: php_fpm_ini_bak

- name: backup php-fpm ini (if required)
  notify: restart php
  shell: 'cp {{php_ini_dir}}/fpm/php.ini {{php_ini_dir}}/fpm/php.ini.original.bak'
  when: php_fpm_ini_bak.stat.exists == False

- name: copy php-fpm ini to server
  notify: restart php
  template: src=php.ini dest='{{php_ini_dir}}/fpm/php.ini'

# cli
- name: get php-cli ini backup stats
  stat: path='{{php_ini_dir}}/cli/php.ini.original.bak' follow=False
  register: php_cli_ini_bak

- name: backup php-cli ini (if required)
  notify: restart php
  shell: 'cp {{php_ini_dir}}/cli/php.ini {{php_ini_dir}}/cli/php.ini.original.bak'
  when: php_cli_ini_bak.stat.exists == False

- name: copy php-cli ini to server
  notify: restart php
  template: src=php.ini dest='{{php_ini_dir}}/cli/php.ini'


# ------------------------------------------------------------------------------
# backup and configure fpm
# ------------------------------------------------------------------------------

- name: get php fpm config backup stats
  stat: path='{{php_ini_dir}}/fpm/php-fpm.conf.original.bak'
  register: php_fpm_config_bak

- name: backup php-fpm config (if required)
  notify: restart php
  shell: 'mv {{php_ini_dir}}/fpm/php-fpm.conf {{php_ini_dir}}/fpm/php-fpm.conf.original.bak'
  when: php_fpm_config_bak.stat.exists == False

- name: copy php-fpm ini to server
  notify: restart php
  template: src=php-fpm.conf dest='{{php_ini_dir}}/fpm/php-fpm.conf'

# ------------------------------------------------------------------------------
# backup and configure fpm default pool
# ------------------------------------------------------------------------------

- name: get php-fpm default pool backup stats
  stat: path='{{php_ini_dir}}/fpm/pool.d/www.conf.original.bak'
  register: php_fpm_default_pool_bak

- name: backup php-fpm default pool (if required)
  notify: restart php
  shell: 'mv {{php_ini_dir}}/fpm/pool.d/www.conf {{php_ini_dir}}/fpm/pool.d/www.conf.original.bak'
  when: php_fpm_default_pool_bak.stat.exists == False

- name: copy php-fpm ini to server
  notify: restart php
  template: src=php.www.conf dest='{{php_ini_dir}}/fpm/pool.d/www.conf'

# ------------------------------------------------------------------------------
# regression: sometimes handler does not properly restart, so there's no socket
# ------------------------------------------------------------------------------

- name: restart php manually
  service:
    name: '{{php_service_name}}'
    state: restarted
