---
# ------------------------------------------------------------------------------
# install php
# ------------------------------------------------------------------------------

- name: add php repositories
  apt_repository: repo="{{php_repository}}"
  when: php_repository is defined and php_repository != False

- name: open ssl and mcrypt
  apt: 
    state: present
    pkg: [
      'mcrypt',
      'openssl'
    ]

- name: install php
  apt: 
    pkg: "{{php_modules}}" 
    state: present
  notify: restart php

- name: ensure php starts at boot
  service: name='{{php_service_name}}' state=started enabled=yes


# ------------------------------------------------------------------------------
# install composer
# ------------------------------------------------------------------------------

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: self update composer
  shell: /usr/local/bin/composer self-update

